name:hopesite
version:1
handle:
- rewrite: if(!is_file() && path ~ "/admin/(.*)") goto "/admin/index.php?m=$1&%{QUERY_STRING}"
- rewrite: if(!is_file() && path ~ "/(.*)") goto "/index.php?m=$1&%{QUERY_STRING}"